### ISSUE TITLE
Installation Exception?

### ISSUE THREAD

**Issue by LordEmer** [Qiqis-Notebook/qnb-client#10]
I downloaded the Setup and Ran it.
There was an Error.
Sorry, I tried to look around for the instructions but I couldn't find any.
I tried to run it with Admin rights too but it gives me same error.
Should I place installation in a certain folder before running it? It has some trouble with finding some files.
README in the sources is about compiling it, not the setup version... No idea...

Here is error Dump:
```
0416> 2023-08-29 18:44:28> Program: Starting Squirrel Updater: --install .
10416> 2023-08-29 18:44:28> Program: Starting install, writing to C:\Users\admnt\AppData\Local\SquirrelTemp
10416> 2023-08-29 18:44:28> Program: About to install to: C:\Users\admnt\AppData\Local\Discord
10416> 2023-08-29 18:44:28> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
10416> 2023-08-29 18:44:28> CheckForUpdateImpl: Reading RELEASES file from C:\Users\admnt\AppData\Local\SquirrelTemp
10416> 2023-08-29 18:44:28> CheckForUpdateImpl: Remote version 1.0.9016 differs from local 
10416> 2023-08-29 18:44:28> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
10416> 2023-08-29 18:44:28> ApplyReleasesImpl: Writing files to app directory: C:\Users\admnt\AppData\Local\Discord\app-1.0.9016
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\app.ico to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\app.ico
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\chrome_100_percent.pak to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\chrome_100_percent.pak
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\chrome_200_percent.pak to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\chrome_200_percent.pak
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\d3dcompiler_47.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\d3dcompiler_47.dll
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\Discord.exe to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\Discord.exe
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\ffmpeg.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\ffmpeg.dll
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\icudtl.dat to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\icudtl.dat
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\installer.db to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\installer.db
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\libEGL.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\libEGL.dll
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\libGLESv2.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\libGLESv2.dll
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\resources.pak to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\resources.pak
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\snapshot_blob.bin to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\snapshot_blob.bin
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\updater.node to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\updater.node
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\vk_swiftshader.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\vk_swiftshader.dll
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\vulkan-1.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\vulkan-1.dll
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\v8_context_snapshot.bin to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\v8_context_snapshot.bin
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\lib\net45\vk_swiftshader_icd.json to C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\vk_swiftshader_icd.json
10416> 2023-08-29 18:44:30> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\Discord.exe]
10416> 2023-08-29 18:44:31> Utility: Process Started: C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\Discord.exe --squirrel-install 1.0.9016, pid 7128
10416> 2023-08-29 18:44:33> Utility: Received exitcode 0 from process C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\Discord.exe
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: ran C:\Users\admnt\AppData\Local\Discord\app-1.0.9016\Discord.exe, pid 7172
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: Starting fixPinnedExecutables
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9016
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: File 'C:\Users\admnt\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\Narrator.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: File 'C:\Users\admnt\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\On-Screen Keyboard.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: Updating shortcut C:\Users\admnt\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: Updating shortcut C:\Users\admnt\OneDrive\Desktop\Discord.lnk
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: Fixing up tray icons
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9016
10416> 2023-08-29 18:44:33> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9016
24720> 2024-05-24 22:34:10> Program: Starting Squirrel Updater: --install .
24720> 2024-05-24 22:34:10> Program: Starting install, writing to C:\Users\admnt\AppData\Local\SquirrelTemp
24720> 2024-05-24 22:34:10> Program: About to install to: C:\Users\admnt\AppData\Local\Discord
24720> 2024-05-24 22:34:10> Program: Install path C:\Users\admnt\AppData\Local\Discord already exists, burning it to the ground
24720> 2024-05-24 22:34:10> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
24720> 2024-05-24 22:34:10> CheckForUpdateImpl: Reading RELEASES file from C:\Users\admnt\AppData\Local\SquirrelTemp
24720> 2024-05-24 22:34:10> CheckForUpdateImpl: Remote version 1.0.9147 differs from local 
24720> 2024-05-24 22:34:10> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
24720> 2024-05-24 22:34:10> ApplyReleasesImpl: Writing files to app directory: C:\Users\admnt\AppData\Local\Discord\app-1.0.9147
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\app.ico to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\app.ico
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\chrome_200_percent.pak to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\chrome_200_percent.pak
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\chrome_100_percent.pak to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\chrome_100_percent.pak
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\d3dcompiler_47.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\d3dcompiler_47.dll
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\Discord.exe.sig to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\Discord.exe.sig
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\Discord.exe to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\Discord.exe
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\ffmpeg.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\ffmpeg.dll
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\icudtl.dat to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\icudtl.dat
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\installer.db to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\installer.db
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\libEGL.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\libEGL.dll
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\libGLESv2.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\libGLESv2.dll
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\resources.pak to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\resources.pak
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\snapshot_blob.bin to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\snapshot_blob.bin
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\v8_context_snapshot.bin to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\v8_context_snapshot.bin
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\vk_swiftshader_icd.json to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\vk_swiftshader_icd.json
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\updater.node to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\updater.node
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\vk_swiftshader.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\vk_swiftshader.dll
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Moving file C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\lib\net45\vulkan-1.dll to C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\vulkan-1.dll
24720> 2024-05-24 22:34:13> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\Discord.exe]
24720> 2024-05-24 22:34:13> Utility: Process Started: C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\Discord.exe --squirrel-install 1.0.9147, pid 26144
24720> 2024-05-24 22:34:15> Utility: Received exitcode 0 from process C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\Discord.exe
24720> 2024-05-24 22:34:15> ApplyReleasesImpl: ran C:\Users\admnt\AppData\Local\Discord\app-1.0.9147\Discord.exe, pid 36580
24720> 2024-05-24 22:34:15> ApplyReleasesImpl: Starting fixPinnedExecutables
24720> 2024-05-24 22:34:15> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9147
24720> 2024-05-24 22:34:15> ApplyReleasesImpl: File 'C:\Users\admnt\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\Narrator.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
24720> 2024-05-24 22:34:15> ApplyReleasesImpl: File 'C:\Users\admnt\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessibility\On-Screen Keyboard.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
24720> 2024-05-24 22:34:16> ApplyReleasesImpl: Updating shortcut C:\Users\admnt\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk
24720> 2024-05-24 22:34:16> ApplyReleasesImpl: Updating shortcut C:\Users\admnt\OneDrive\Desktop\Discord.lnk
24720> 2024-05-24 22:34:16> ApplyReleasesImpl: Fixing up tray icons
24720> 2024-05-24 22:34:16> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9147
24720> 2024-05-24 22:34:16> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9147
```

**Comment by Kennie-L** [comment]
Heyo sorry for the late response, the log file you sent does not include anything related to this installation so it's likely the installation didn't even start.

Common problems with this is either anti-virus or conflict with discord (as seen from logs) as they use the same installer as we do.
You can try pausing your anti-virus or navigating to `/AppData/Local` and deleting the `SquirrelTemp` folder before trying again.
> To navigate to the AppData directory on windows, search `%appdata% on your windows searchbar.

**Comment by LordEmer** [comment]
Oh deleting the SquirrelTemp folder made it work.
Great website and this tool is superb. Thanks for making it!!
